### ISSUE TITLE
Where is your color palette defined?

### ISSUE THREAD

**Issue by bknowles** [sqshq/sampler#1]
I'm trying to run your `runcharts.yml` example, but I'm not a fan of the color you chose for Google.  It seems to me that it is closer to the color that should be used for Yahoo.

So, this has sent me down the rathole of trying to figure out where your color palette is defined, so that I can find the appropriate Web-safe or HTML color that would most appropriately represent different entities, and then map that back to the closest matching 8-bit color.

But I can't find anything anywhere in your repo that makes this mapping obvious.

Can you help me out here?  Is there a standard Go reference that I'm not aware of?  Thanks!

**Comment by sqshq** [comment]
Hi @bknowles 
The colors for both dark and light theme are defined here:
https://github.com/sqshq/sampler/blob/master/console/palette.go

Basically it is a number of predefined colors, which will be set for the lines on the chart it user did not specified his own colors.

In this example GOOGLE has user-defined color (178), and YAHOO color is taken from the predefined list.

```
runcharts:
  - title: Search engine response time
    rate-ms: 500        # sampling rate, default = 1000
    scale: 2            # number of digits after sample decimal point, default = 1
    legend:
      enabled: true     # enables item labels, default = true
      details: false    # enables item statistics: cur/min/max/dlt values, default = true
    items:
      - label: GOOGLE
        sample: curl -o /dev/null -s -w '%{time_total}'  https://www.google.com
        color: 178      # 8-bit color number, default one is chosen from a pre-defined palette
      - label: YAHOO
        sample: curl -o /dev/null -s -w '%{time_total}'  https://search.yahoo.com
```

So if you don't like the default ones, you can specify your own color for each of the lines on your chart

**Comment by bknowles** [comment]
@sqshq -- Okay, so if I understand correctly, then according to that table, Google should be shown in "ColorOlive", correct?

I gave this a shot, and the colors seem to be off to me.  I also posted a screenshot to imgur at https://imgur.com/RTCRf22, in case I'm not able to attach it here:

<img width="2072" alt="Screen Shot 2019-07-31 at 4 50 29 PM" src="https://user-images.githubusercontent.com/1151895/62250859-b218d300-b3b3-11e9-930f-1799eee83eea.png">

To me, that color looks more like yellow, not anything I would recognize as "olive".  And I'm also confused as to how those other colors get chosen -- Yahoo is shown in a light blue color, and Bing is shown in a Pinkish color.  Is there some lookup table or other formula that I am missing?

**Comment by bknowles** [comment]
I can find plenty of charts of web-safe colors and their specific RGB components or hex codes, but it's not clear to me how I could make the line for Yahoo to reasonably closely match their official corporate Purple color.  How do I find out what all the 256 colors are and what indexes map to what RGB values?

**Comment by sqshq** [comment]
Sampler has nothing to do with Google or Yahoo. This is an abstract example for sampling a search engine response time using the curl command. 

If you'd like to change a color of a the line - just specify anything in range from 0 to 255. See [8 bit colors cheat sheet](https://jonasjacek.github.io/colors/)

`Olive` is the Xterm color name for `178`

**Comment by bknowles** [comment]
Okay, that cheat sheet is what I was missing!

Can we get that linked into the documentation, or somewhere else?

**Comment by bknowles** [comment]
Now that I have this key piece of information, I can make the colors look much more brand-appropriate!

<img width="2072" alt="Screen Shot 2019-08-01 at 9 17 21 AM" src="https://user-images.githubusercontent.com/1151895/62300932-4418ee00-b43d-11e9-8a61-ff3ffccc90ef.png">

Thanks again!

**Comment by bknowles** [comment]
BTW, here is what my `runcharts.yml` now looks like:

```
runcharts:
  - title: Search engine response time
    rate-ms: 500        # sampling rate, default = 1000
    scale: 2            # number of digits after sample decimal point, default = 1
    legend:
      enabled: true     # enables item labels, default = true
      details: false    # enables item statistics: cur/min/max/dlt values, default = true
    items:
      - label: GOOGLE
        sample: curl -o /dev/null -s -w '%{time_total}'  https://www.google.com
        color: 178      # 8-bit color number, default one is chosen from a pre-defined palette
      - label: YAHOO
        sample: curl -o /dev/null -s -w '%{time_total}'  https://search.yahoo.com
        color: 91	# See cheat sheet at https://jonasjacek.github.io/colors/
      - label: BING
        sample: curl -o /dev/null -s -w '%{time_total}'  https://www.bing.com
        color: 29	# See cheat sheet at https://jonasjacek.github.io/colors/
```

If you would like me to file a PR for this, please let me know.  I'm happy to help.
