### ISSUE TITLE
Sampler freezes after spawing a lot of processes (on server)

### ISSUE THREAD

**Issue by dadyarri** [sqshq/sampler#101]
![image](https://user-images.githubusercontent.com/51821039/104119683-32ca5580-5342-11eb-888f-8aa493e46b54.png)

Is it error in config or bug?
```yaml
runcharts:
  - title: VK's response time
    position: [[42, 16], [38, 25]]
    rate-ms: 500
    triggers:
      - title: Latency threshold exceeded
        condition: echo "$prev < 0.3 && $cur > 0.3" |bc -l
        actions:
            terminal-bell: true
            sound: true
            visual: true
            script: 'say alert: ${label} latency exceeded ${cur} second'
    legend:
        enabled: true
        details: false
    scale: 2
    items:
      - label: VK
        color: 178
        sample: curl -o /dev/null -s -w '%{time_total}'  https://www.vk.com
sparklines:
  - title: CPU Usage
    position: [[57, 9], [23, 8]]
    rate-ms: 200
    scale: 0
    sample: ps -A -o %cpu | awk '{s+=$1} END {print s}'
  - title: RAM Usage
    position: [[57, 0], [23, 9]]
    rate-ms: 200
    scale: 0
    sample: echo "scale=1; $(vmstat -s | grep 'used memory' | awk '{print $1}') /
        $( vmstat -s | grep 'total memory' | awk '{print $1}') * 100" | bc
textboxes:
  - title: Docker containers stats
    position: [[0, 9], [57, 8]]
    rate-ms: 500
    sample: docker stats --no-stream --format "table {{.Name}} \t{{.CPUPerc}}\t{{.MemUsage}}\t{{.NetIO}}\t{{.BlockIO}}\t{{.PIDs}}"
  - title: Docker logs
    position: [[0, 16], [42, 25]]
    rate-ms: 500
    sample: cd ~/projects/choco; docker-compose logs --tail=0 --follow
asciiboxes:
  - title: Current time (Europe/Moscow)
    position: [[0, 0], [31, 9]]
    rate-ms: 500
    color: 43
    sample: date +%H:%M:%S
```
