### ISSUE TITLE
Strange behavior on asciiboxes > sample command not well interpreted (bad yaml ?)

### ISSUE THREAD

**Issue by adriens** [sqshq/sampler#116]
# :grey_question: Context

Hi, I want to build a fun geeky creation based on `sampler`, around the [Programmer's Day](https://en.wikipedia.org/wiki/Day_of_the_Programmer).

# :point_right: Description

I have built the following script that does the stuff : 

```shell
dotp=`date --date="${fdoy} + 255 days" +'%s'`
today=`date +%s`
diff=`expr $dotp - $today`
diff=$((diff / 86400))
echo $diff
```

... then put it in a sampler conf : 

```yaml
asciiboxes:
  - title: Days Before Programmers day Of the Year ⏳
    rate-ms: 500        # sampling rate, default = 1000
    font: 3d            # font type, default = 2d
    border: true        # border around the item, default = true    
    color: 43           # 8-bit color number, default is white
    sample: |
            dotp=`date --date="${fdoy} + 255 days" +'%s'` ; today=`date +%s` ; diff=`expr $dotp - $today` ; diff=$((diff / 86400)) ; echo $diff
```

:point_up:  But I only manage to get `255` : 

![image](https://user-images.githubusercontent.com/5235127/166098871-64b3678f-d4c8-4e87-84a9-f6b86235bd6d.png)

So I guess I did badly formatted my `yaml`.

:pray: Could you please point me what's wrong with my `sampler` configuration ?`
