### ISSUE TITLE
:grey_question:  Layout question (jq | column)

### ISSUE THREAD

**Issue by adriens** [sqshq/sampler#117]
# :point_right: Context

I'm preparing of ready to use sample dashboards. At the end i'll create a dedicated & public GH repo.

# :grey_question: Question about alignement

I would like to get the following command in a nice looking way in sampler.

Everything looks fine from the terminal : 

```shell
curl -s https://hub.docker.com/v2/repositories/optnc | jq -r '"Image\tStars\tPulls", "-----------------------\t-------\t------", ( .results | sort_by(.pull_count) | reverse | .[] | "\(.name)\t\(.star_count)\t\(.pull_count)")' | column -t -s $'\t'
```

see below : 

![image](https://user-images.githubusercontent.com/5235127/166123107-18164df7-b0bf-4e3f-a01c-0d29ce49c26d.png)

... but when I put the same commad in the following conf : 

```yaml
textboxes:
  - title: OPT-NC Docker image stats
    rate-ms: 15000
    sample: curl -s https://hub.docker.com/v2/repositories/optnc | jq -r '"Image\tStars\tPulls", "-----------------------\t-------\t------", ( .results | sort_by(.pull_count) | reverse | .[] | "\(.name)\t\(.star_count)\t\(.pull_count)")' | column -t -s $'\t'
```

I get the following render : 

![image](https://user-images.githubusercontent.com/5235127/166123153-0597ace4-5316-4afe-b361-3df94bf372ea.png)

Any idea about what I'm doing wrong ?... or am missing in fomratin options ?

Thank you in advance for any help or feedback.
