### ISSUE TITLE
how to show two digit number in windows?

### ISSUE THREAD

**Issue by tae0y** [sqshq/sampler#126]
- **What should I do for to two digit number in Windows.**
please give your warm advice
and if you need information please let me know.
  
- **Now, `echo 33` looks like this**
![image](https://user-images.githubusercontent.com/20028607/233884646-d040e1ea-99b3-40af-8646-9fd7bbdfe078.png)
sampler version is 1.1.0 (windows 10, SH is installed)
and config.yml is here
```yml
textboxes:
  - title: echo nums
    position: [[0, 0], [80, 11]]
    rate-ms: 500
    sample: echo 33
```
  
- **when execute `echo 33` in sh**
![image](https://user-images.githubusercontent.com/20028607/233884839-9da01cb2-ce31-4171-a8c4-79987c222a03.png)
