### ISSUE TITLE
windows textboxes newline not working

### ISSUE THREAD

**Issue by tae0y** [sqshq/sampler#129]
I'm happily using sampler for monitoring dev/test servers in local PC. thanks a lot!!  
**but in textboxes, newlines does not persist properly**  
I want to know any tweaks to persist newlines in sampler textboxes
I know sampler does not officially support windows, very sad...
  
### my environments
- sampler 1.1.0
- windows 10
- powershell 5.1
  
### here is config
```
textboxes:
  - title: JEUS
    rate-ms: 18000000
    sample: powershell -ExecutionPolicy Unrestricted "'0'+(Get-JEUSSTATUS)"
```
  
### when I run sampler
![image](https://github.com/sqshq/sampler/assets/20028607/d0921700-02bc-4f1e-9d5c-70bf2f4ea661)
  
### when I run it in cmd/sh
![image](https://github.com/sqshq/sampler/assets/20028607/f73886de-2a30-4c08-9016-393301492cf9)
  
### powershell funtion I call (example)
```
function Get-JEUSSTATUS {
    $logs = (/* Getting logs remotely */)
    Wirte-Output $logs
}
```
