### ISSUE TITLE
Allow nested components

### ISSUE THREAD

**Issue by pjmp** [sqshq/sampler#20]
It'd be nice to have something like:
```
--- My dashboard ----------------
| Component:1     | Component:2 |
|                               |
| Component:3                   |
---------------------------------
```

**Comment by vcavallo** [comment]
it seems like it’s just the parent container name “My Dashboard” you’re after, right? otherwise you could have three separate components and arrange them as you have in the diagram.

**Comment by pjmp** [comment]
Yeah pretty much.

**Comment by sqshq** [comment]
Hey @pjmp,
Is it purely for visualization (logical separation of area with a single title "My dashboard"), or you expect something more, like resize and move of the whole group?

**Comment by pjmp** [comment]
In my use case, i was thinking of just having a bordered box with title not expecting it to be moved, however others might have different use cases tho.

**Comment by sqshq** [comment]
In this case I would suggest to not comlicate current layout with nesting support, but just use an empty `textbox`:

```yaml
textboxes:
  - title: My dahsboard
    position: [[14, 9], [47, 23]]
    sample: echo "" # JUST ECHO EMPTY STRING HERE
runcharts:
  - title: Search engine response time
    position: [[15, 19], [45, 12]]
    items:
      - label: GOOGLE
        color: 178
        sample: curl -o /dev/null -s -w '%{time_total}'  https://www.google.com
      - label: YAHOO
        sample: curl -o /dev/null -s -w '%{time_total}'  https://search.yahoo.com
sparklines:
  - title: CPU usage
    position: [[15, 10], [22, 8]]
    rate-ms: 200
    scale: 0
    sample: ps -A -o %cpu | awk '{s+=$1} END {print s}'
  - title: Free memory pages
    position: [[37, 10], [23, 8]]
    rate-ms: 200
    scale: 0
    sample: memory_pressure | grep 'Pages free' | awk '{print $3}'
```

<img width="1024" alt="Screen Shot 2019-08-05 at 7 25 17 PM" src="https://user-images.githubusercontent.com/6069066/62500997-c47d7d00-b7b6-11e9-92b0-497bf907652e.png">
