### ISSUE TITLE
2019/08/07 13:37:30 Failed to read config file: yaml: line 51: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by jbunce** [sqshq/sampler#32]
Using the `example.yml`

sampler --config example.yml                                                                                                                                                                                             
2019/08/07 13:37:30 Failed to read config file: yaml: line 51: mapping values are not allowed in this context

**Comment by JafarAkhondali** [comment]
Sample problem here

**Comment by sqshq** [comment]
Hi @jbunce, @JafarAkhondali 
What's your OS and sampler version?

**Comment by JafarAkhondali** [comment]
@sqshq 
`1.0.2 `
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

**Comment by sqshq** [comment]
I'm trying to reproduce it -

```shell
docker run -it debian
apt update
apt install wget
apt install libasound2-dev
wget https://github.com/sqshq/sampler/releases/download/v1.0.2/sampler-1.0.2-linux-amd64 -O /usr/local/bin/sampler
chmod +x /usr/local/bin/sampler
wget https://raw.githubusercontent.com/sqshq/sampler/master/example.yml
sampler -c example.yml
```

Everything works as expected, no issues with yaml parsing

Does this peace alone work for you?

```yaml
gauges:
  - title: DAY PROGRESS
    position: [[45, 3], [35, 2]]
    cur:
      sample: date +%H
    max:
      sample: echo 24
    min:
      sample: echo 0
```

How about this one?

```yaml
gauges:
  - title: DAY PROGRESS
    position: [[45, 3], [35, 2]]
    cur:
      sample: "date +%H"
    max:
      sample: echo 24
    min:
      sample: echo 0
```
