### ISSUE TITLE
Linux/Ubuntu useful configurations/pipes thread

### ISSUE THREAD

**Issue by WaffleMongeringShit** [sqshq/sampler#34]
Hi,

This topic is dedicated to sharing useful pipes that enhances the sampler experience on GNU/Linux/Ubuntu. Don't hesistate to share! Here are mines:

**HTOP**
_Requires: aha, html2text_
```
textboxes:
  - title: HTOP
    position: [[0, 0], [54, 12]]
    rate-ms: 1000
    color: 122
    sample: echo q | htop -C | aha --line-fix | html2text -width 999 | grep -v "F1Help\|xml version="
```

**HTOP OVER SSH**
_Requires: aha, html2text_
_Warning: Significant CPU load on devices such as raspberry pi._

```
textboxes:
  - title: HTOP
    position: [[0, 28], [48, 12]]
    rate-ms: 1000
    color: 121
    pty: true
    init: ssh -i ~/.ssh/id_rsa user@host
    sample: echo q | htop -C | aha --line-fix | html2text -width 999 | grep -v "F1Help\|xml version="
```
**POSTGRESQL single line query**

```
barcharts:
  - title: Database Distribution
    rate-ms: 180000
    scale: 0
    items:
      - label: Record Count
        sample: PGPASSWORD=PASSWORD psql -h host -U user --no-align --tuples-only -c 'select count(*) from tablename'
```
**Periodic directory count**
_Requires: [dircnt](https://github.com/ChristopherSchultz/fast-file-count)_
```
barcharts:
  - title: Directory Counts
    rate-ms: 180000
    scale: 0
    items:
      - label: Master
        sample: /path/to/dircnt /path/to/target/directory/ | awk {'print $3'}
```

**Comment by sqshq** [comment]
Hey @WaffleMongeringShit, thank you for sharing and starting the thread! I've pinned it.

btw I recommend to use init script to establish the database connection, otherwise it will be done each time the sample script is executed, which might cause unnecessary CPU utilization at higher update rates

**Comment by aimbot31** [comment]
Kubernetes RAM, CPU, Events : 
Requires : kubectl with a valid configuration
```
runcharts:
  - title: K8S Node Ram Usage
    position: [[0, 20], [40, 20]]
    rate-ms: 5000
    legend:
        enabled: true
        details: false
    scale: 0
    items:
      - label: node1
        color: 178
        sample: kubectl top nodes | awk 'NR==2 {printf "%d", $5}'
      - label: node2
        sample: kubectl top nodes | awk 'NR==3 {printf "%d", $5}'
      - label: node4
        sample: kubectl top nodes | awk 'NR==4 {printf "%d", $5}'
  - title: K8S Node CPU Usage
    position: [[40, 20], [40, 20]]
    rate-ms: 5000
    legend:
        enabled: true
        details: false
    scale: 0
    items:
      - label: node1
        color: 178
        sample: kubectl top nodes | awk 'NR==2 {printf "%d", $3}'
      - label: node2
        sample: kubectl top nodes | awk 'NR==3 {printf "%d", $3}'
      - label: node4
        sample: kubectl top nodes | awk 'NR==4 {printf "%d", $3}'
textboxes:
  - title: Kubernetes events
    position: [[0, 0], [80, 20]]
    rate-ms: 3000
    color: 211
    sample: kubectl get events -A | grep -e "Failed" -e "NAMESPACE"
```

**Comment by Asherslab** [comment]
[Request] 
Could someone make something for some nice Docker Swarm metrics?
Node metrics (maybe cpu and such) and stack metrics?

**Comment by Asherslab** [comment]
On another note. lemme throw in my small (and stupidly complicated) Bash script, and config, for github issues/pr count viewing.

BTW, only my second time writing a bash script. don't stab me =P

https://gist.github.com/Asherslab/2553dc63a95702563007e193e93878ae

a few example sections using the script:

Requirements: All these scripts require the `jq` bash command, plus the script above (yeah it's death)


View your projects open PRs vs Closed (in a gauge)
```
gauges:
  - title: "[ChatChain] Open Prs"
    rate-ms: 300000
    percent-only: false
    color: 178
    cur:
      sample: ./github.sh -n -r ldtteam/chatchain -s open -t pr
    max:
      sample: ./github.sh -n -r ldtteam/chatchain -s total -t pr
    min:
      sample: echo 0
```

View your project's open Issues vs Closed (in a gauge)
```
gauges:
  - title: "[ChatChain] Open Issues"
    rate-ms: 300000
    percent-only: false
    cur:
      sample: ./github.sh -n -r ldtteam/chatchain -s open -t issue
    max:
      sample: ./github.sh -n -r ldtteam/chatchain -s total -t issue
    min:
      sample: echo 0
```

View all stats in a simple text box
```
textboxes:
  - title: "[ChatChain] Status"
    position: [[1, 6], [23, 35]]
    rate-ms: 300000
    sample: ./github.sh -r ldtteam/chatchain
```

Note: there are rate limits on github's API. (you can increase them by using an API Key with the -u and -p parameters) 

Note2: Large repositories take a decent while to load/whatever. The script could very much be improved. i'm probably gonna redo it in python or something similar at a later point. maybe

**Comment by Asherslab** [comment]
So, after a days work. i improved upon my thing above. 
Now, it's python, and faster, and better. does sometimes error though.

Python3 script: https://gist.github.com/Asherslab/1f37627854e913b86f088aa8ca30e8d0

i use a cache file to keep just one session accessing the api, so this is needed for all the elements below it:

```
textboxes:
  - title: ""
    position: [[0, 0], [0, 0]]
    rate-ms: 1800000
    sample: github/main.py output -k <GITHUB OAUTH KEY> -r ldtteam/minecolonies -f cache.json -l > /dev/null
    border: false
```

Sparklines for open and closed issues

```
sparklines:
  - title: Open Issues
    position: [[0, 6], [40, 9]]
    rate-ms: 2000
    sample: cat cache.json | github/main.py input -si -v issues.open
  - title: Closed Issues
    position: [[40, 6], [40, 9]]
    rate-ms: 2000
    sample: cat cache.json | github/main.py input -si -v issues.closed
```

Runcharts for issue labels

```
runcharts:
  - title: Issues
    position: [[0, 20], [80, 20]]
    rate-ms: 2000
    legend:
        enabled: true
        details: false
    scale: 2
    items:
      - label: Bug
        sample: cat cache.json | github/main.py input -si -v issues.labels.bug.open
      - label: Invalid
        sample: cat cache.json | github/main.py input -si -v issues.labels.invalid.open
      - label: Question
        sample: cat cache.json | github/main.py input -si -v issues.labels.question.open
      - label: In Progress
        sample: cat cache.json | github/main.py input -si -v issues.labels.in_progress.open
```

Text box for some data:
```
textboxes:
  - title: Pull Requests
    position: [[0, 15], [20, 5]]
    rate-ms: 2000
    sample: cat cache.json | github/main.py input -si --verbose -v pull_requests.open pull_requests.closed pull_requests.total pull_requests.labels.hotfix.open
```
ASCII box that uses the repo's name:
```
asciiboxes:
  - title: name
    position: [[0, 0], [26, 6]]
    rate-ms: 2000
    sample: cat cache.json | github/main.py input -si -v name
```
