### ISSUE TITLE
Failed to parse a number: strconv.ParseFloat on Runcharts

### ISSUE THREAD

**Issue by WaffleMongeringShit** [sqshq/sampler#7]
Set up exactly like in the tutorial. Running on ubuntu. 

```
runcharts:
  - title: Search engine response time
    rate-ms: 500        # sampling rate, default = 1000
    scale: 2            # number of digits after sample decimal point, default = 1
    legend:
      enabled: true     # enables item labels, default = true
      details: false    # enables item statistics: cur/min/max/dlt values, default = true
    items:
      - label: GOOGLE
        sample: curl -o /dev/null -s -w '%{time_total}'  https://www.google.com
        color: 178      # 8-bit color number, default one is chosen from a pre-defined palette
      - label: YAHOO
        sample: curl -o /dev/null -s -w '%{time_total}'  https://search.yahoo.com
      - label: BING
        sample: curl -o /dev/null -s -w '%{time_total}'  https://www.bing.com
```
![error](https://user-images.githubusercontent.com/50962064/62412317-5f385900-b609-11e9-8276-458d4bff72ff.png)

Sample output from 'curl -o /dev/null -s -w '%{time_total}'  https://www.bing.com' : 0,435571
