### ISSUE TITLE
rate-ms appears to be not honoured in gauges

### ISSUE THREAD

**Issue by tastytea** [sqshq/sampler#74]
I've set `rate-ms` to 10000 but it is updated at least once a second. The full block is:

```YAML
gauges:
  - title: Memory used (MiB)
    position: [[0, 20], [20, 4]]
    rate-ms: 10000
    scale: 0
    color: 58
    cur:
      sample: env LC_ALL=C free -m | grep ^Mem | awk '{print $3}'
    max:
      sample: env LC_ALL=C free -m | grep ^Mem | awk '{print $2}'
    min:
      sample: echo 0
    triggers:
      - title: Low memory
        condition: '[ $label == "cur" ] && [ $cur -ge 15000 ] && echo 1 || echo 0'
        actions:
            visual: true
```
