### ISSUE TITLE
Text output mangled in textbox

### ISSUE THREAD

**Issue by Hubbitus** [sqshq/sampler#84]
F.e. on terminal I see:
```
$ fgrep 'DONE process' '/srv/rdc-emr/tables/2_create_all_snapshots.2020-01-15T09:28:14+0000.log' | cat --number
     1  DONE process [./Entity]
     2  DONE process [./EntityAddress]
     3  DONE process [./EventSubCategory]
     4  DONE process [./GridBizUnit]
     5  DONE process [./FirmInfo]
     6  DONE process [./EventCategory]
     7  DONE process [./Event]
     8  DONE process [./EntityAbstract2]
     9  DONE process [./InquiryMatch]
    10  DONE process [./GridMatch]
    11  DONE process [./DateOfBirth]
    12  DONE process [./EntityRelationship]
    13  DONE process [./ClientAlertDecReview]
    14  DONE process [./ClientAlertDecMatch]
    15  DONE process [./EntitySource]
    16  DONE process [./ItemPublication]
    17  DONE process [./ClientAlertDecReason]
    18  DONE process [./GridBatch]
```
In `sampler` with configuration:
```
textboxes:
  - title: Debug!
    rate-ms: 1000
    pty: true  # enables pseudo-terminal mode, default = false
    init: ssh -i ~/.ssh/id_rsa.rdc-emr-all hadoop@10.64.19.220 bash
    sample: fgrep 'DONE process' '/srv/rdc-emr/tables/2_create_all_snapshots.2020-01-15T09:28:14+0000.log' | cat --number
```
it looks like:
![image](https://user-images.githubusercontent.com/720349/72427462-d5d2a880-379c-11ea-90b0-800a457bd54e.png)
