### ISSUE TITLE
Variables do not processed if init command used

### ISSUE THREAD

**Issue by Hubbitus** [sqshq/sampler#85]
Config:
```
variables:
    qas_emr_connection: /usr/bin/ssh -i ~/.ssh/id_rsa.rdc-emr-all hadoop@10.64.19.220
    watch_file: /srv/rdc-emr/tables/3_add_all_hours.2020-01-15T18:00:16+0000.log
textboxes:
  - title: Echo variable localy
    sample: echo "File=$watch_file"
  - title: Echo variable remote
    pty: true
    init: $qas_emr_connection bash
    sample: echo "File=$watch_file"
```
Output:
![image](https://user-images.githubusercontent.com/720349/72461514-39ca9080-37e0-11ea-8383-fd7aec878506.png)
