### ISSUE TITLE
SSH - Top doesn't work on Ubuntu to RPi connection

### ISSUE THREAD

**Issue by WaffleMongeringShit** [sqshq/sampler#9]
```
textboxes:
  - title: SSH
    pty: false
    init: ssh -i /home/user/.ssh/id_rsa.pub -t user@host
    sample: top
```

Text box reports the following:

```
SAMPLING FAILURE
exec: not started
```
